# Tcl script generated by PlanAhead

set reloadAllCoreGenRepositories false

set tclUtilsPath "c:/Xilinx/14.7/ISE_DS/PlanAhead/scripts/pa_cg_utils.tcl"

set repoPaths ""

set cgIndexMapPath "Z:/Dev/hc800/nexys3/hc800.srcs/sources_1/ip/cg_nt_index_map.xml"

set cgProjectPath "z:/Dev/hc800/nexys3/hc800.srcs/sources_1/ip/blk_mem_gen_v7_3_2/coregen.cgc"

set ipFile "z:/Dev/hc800/nexys3/hc800.srcs/sources_1/ip/blk_mem_gen_v7_3_2/AttributeMemory.xco"

set ipName "AttributeMemory"

set hdlType "Verilog"

set cgPartSpec "xc6slx16-3csg324"

set chains "GENERATE_CURRENT_CHAIN"

set params ""

set bomFilePath "z:/Dev/hc800/nexys3/hc800.srcs/sources_1/ip/blk_mem_gen_v7_3_2/pa_cg_bom.xml"

# generate the IP
set result [source "c:/Xilinx/14.7/ISE_DS/PlanAhead/scripts/pa_cg_gen_out_prods.tcl"]

exit $result

