	IFND	BLOCKDEVICE_SD_I_INCLUDED__

BLOCKDEVICE_SD_I_INCLUDED__ = 1

BLOCKDEVICE_SDA		EQU	0
BLOCKDEVICE_SDA0	EQU	1
BLOCKDEVICE_SDA1	EQU	2
BLOCKDEVICE_SDA2	EQU	3
BLOCKDEVICE_SDB		EQU	4
BLOCKDEVICE_SDB0	EQU	5
BLOCKDEVICE_SDB1	EQU	6
BLOCKDEVICE_SDB2	EQU	7

TOTAL_BLOCKDEVICES	EQU	8

		RSRESET
bdev_Read	RW	1
bdev_Write	RW	1
bdev_Size	RW	1
bdev_PRIVATE	RB	0

		GLOBAL	BlockDeviceInit
		GLOBAL	BlockDeviceGet
		GLOBAL	BlockDeviceRead

	ENDC