	IFND	KERNEL_ERROR_I_INCLUDED__

KERNEL_ERROR_I_INCLUDED__ = 1

			RSRESET
ERROR_PROTOCOL		RB	1
ERROR_TIMEOUT		RB	1
ERROR_SUCCESS		RB	1
ERROR_NOT_AVAILABLE	RB	1
ERROR_FORMAT		RB	1
ERROR_last		RB	0

		GLOBAL	ErrorPrintDescription

	ENDC
