	IFND	LOWLEVEL_SD_I_INCLUDED__

LOWLEVEL_SD_I_INCLUDED__ = 1

SDTYPE_NONE	EQU	0
SDTYPE_V1	EQU	1
SDTYPE_V2	EQU	2
SDTYPE_V2_HC	EQU	3

		GLOBAL	SdInit
		GLOBAL	SdGetTotalBlocks
		GLOBAL	SdReadSingleBlock
		GLOBAL	SdWriteSingleBlock

		GLOBAL	SdType
		GLOBAL	SdSelect

	ENDC
