	IFND	MMU_I_INCLUDED_

MMU_I_INCLUDED_ = 1

MMU_CFG_KERNEL	EQU	$00
MMU_CFG_LOAD	EQU	$01
MMU_CFG_CLIENT	EQU	$02
MMU_CFG_SPARE	EQU	$03

MMU_CONFIG_SIZE	EQU	9

	GLOBAL	MmuInitialize
	GLOBAL	MmuActivateConfig
	GLOBAL	MmuSetConfigCode
	GLOBAL	MmuSetConfigData


	ENDC