	IFND	NEXYS3_I_INCLUDED_

NEXYS3_I_INCLUDED_ = 1

	GLOBAL	CheckButtons
	GLOBAL	SetHexSegments

IO_NEXYS3_BASE		EQU	$80

; 7 segment displays

IO_NEXYS3_HEX_LOWER	EQU	$00
IO_NEXYS3_HEX_UPPER	EQU	$01

; 5 directional buttons

IO_NEXYS3_BUTTONS	EQU	$10

IO_BUTTON_CENTER	EQU	$01
IO_BUTTON_UP		EQU	$02
IO_BUTTON_LEFT		EQU	$04
IO_BUTTON_DOWN		EQU	$08
IO_BUTTON_RIGHT		EQU	$10

	ENDC
